labs15-music-meteorologist/frontend

README.md

Updated the links to the deployed front ends
Remove any items which are not applicable.

Docs deployment update

---

netlify.toml

Co-authored-by: Ben Feole <bfeole@gmail.com>
Co-authored-by: Sascha Majewsky <sascha.majewsky@pm.me>
Added toml file to deploy to Netlify.

Added toml file

---

music-app/package.json
music-app/src/App.js
music-app/src/index.js
music-app/yarn.lock

replaced tracking ID in index instead of app.js

Refactored GAID

---

music-app/src/actions/index.js
music-app/src/components/LikedSongs.js
music-app/src/reducers/usersReducer.js

Now able to GET user data and view it in browser.

Now able to GET and view User data

---

music-app/src/actions/index.js
music-app/src/components/LikedSongs.js
music-app/src/reducers/usersReducer.js

Now able to logout and redirect to homepage

Feature branch logout

---

music-app/src/App.js
music-app/src/actions/index.js
music-app/src/components/Auth.js
music-app/src/components/Helloworld.js
music-app/src/components/LikedSongs.js
music-app/src/components/Song.js
music-app/src/reducers/index.js
music-app/src/reducers/trackInfoReducer.js

Fixed a refresh bug loading up the users liked songs by saving token in the action instead of the component. 
Co-authored-by: Rushi Arumalla <rushi44@gmail.com>
Co-authored-by: Ben Feole <bfeole@gmail.com>
Co-authored-by: Daniel Starling <danielstarling4@gmail.com>
Co-authored-by: Sascha Majewsky <sascha.majewsky@pm.me>

Fixed loading on liked songs

---

music-app/src/components/Footer.js
music-app/src/components/LikedSongs.js
music-app/src/components/Player.js

Added a simple footer to the main page, the links are not working yet until we make those pages out.

Made a simple footer with Material-UI

---

music-app/src/App.js
music-app/src/components/Auth.js
music-app/src/components/NavBar.js

Feature branch NavBar

---

music-app/src/App.css
music-app/src/components/dashbaord/LikedSongs.js
music-app/src/index.css
music-app/src/views/Dashboard.js

 Added toggle feature for liked songs and shifted logout button

---

music-app/src/App.css
music-app/src/components/dashboard/MusicPlayer.js

Refactored mobile view to switch to columns and styled appropriately when under 600px width. 

Mobile view now showing components as column

---

music-app/src/App.css
music-app/src/actions/index.js
music-app/src/components/Auth.js
music-app/src/components/Characteristics.js
music-app/src/components/Chart.js
music-app/src/components/dashboard/LikedSongs.js
music-app/src/components/dashboard/MusicPlayer.js
music-app/src/components/protected.route.js
music-app/src/views/Dashboard.js
music-app/src/views/Info.js

When a user is already saved in the db by its spotify_id it gets updated for the current API_key and when he is a new user he gets signed up. Tested with 2 accounts.

Added storage of spotify users to backend

---

music-app/src/App.css
music-app/src/actions/index.js
music-app/src/components/dashboard/LikedSongs.js

Mobile view footer is now working, and got rid of users in the liked songs tab

Fixed footer in mobile view and got rid of Users in liked songs tab

---

music-app/src/actions/index.js
music-app/src/components/Auth.js
music-app/src/components/NavBar.js

Dispatches without any logic to it were leading to errors. We don't need to bring in data back into our redux store through the dispatches so for now they are disabled. The persistence is happening for new and for known users.

Fixxed user database persistence

---

music-app/src/components/Characteristics.js

Key: https://en.wikipedia.org/wiki/Pitch_class
Mode: 0 is minor and 1 is major 
https://developer.spotify.com/documentation/web-api/reference/tracks/get-audio-features/

Added convertion for mode and key to readable format

---

music-app/src/App.css
music-app/src/components/Characteristics.js

Added a transition effect to the like and dislike button

Improved animations of feedback system

---

music-app/src/App.css
music-app/src/components/dashboard/AudioDetails.js
music-app/src/components/dashboard/MusicPlayer.js
music-app/src/views/Dashboard.js

Feature Branch Question - AudioDetails

---

music-app/src/actions/index.js
music-app/src/components/dashboard/LikedSongs.js
music-app/src/components/dashboard/MusicPlayer.js
music-app/src/reducers/getPlaylistReducer.js
music-app/src/views/Dashboard.js

Create playlist action working, still need to remove hardcoded user id to create. Get playlist action and reducers built. Still need to be hooked up to dynamic id's. Data is loading with hardcoded id's. Needs more work to get playlist id from backend, and to remove hardcoded user and playlist ids once ready.
UI components still not updated to visually render the playlist.

added getPlaylist action and reducers, starting to connect to UI.

---

music-app/src/App.css
music-app/src/components/Auth.js
music-app/src/components/Footer.js
music-app/src/components/dashboard/MusicPlayer.js
music-app/src/views/styles/homepage.css

Now looking good on Tablet(1200px)

Fixed up tablet view and fixed some error messages in console :lipstick:

---

music-app/src/components/dashboard/MusicPlayer.js

The prediction percentage is now dynamic and changes with song.

Feature branch dynamic prediction

---

music-app/src/components/dashboard/LikedSongs.js
music-app/src/components/dashboard/MusicPlayer.js

Playlist now showing songs in queue

---

music-app/src/actions/index.js
music-app/src/components/dashboard/LikedSongs.js
music-app/src/components/dashboard/MusicPlayer.js
music-app/src/views/Dashboard.js

Page now loading on render smoothly

Patch branch render loading

---

music-app/src/components/dashboard/MusicPlayer.js

For some reason imageSpotify didn't get merged earlier

imageSpotify did not get merged in earlier for some reason

---

music-app/src/components/dashboard/MusicPlayer.js
music-app/src/views/Dashboard.js

Now adds songs coming in from DS to music-meteorlogist playlist on spotify on login

Adds Songs on Login / Player now dynamically takes in users playlist 

---

music-app/src/components/LinearDeterminate.js
music-app/src/components/dashboard/LikedSongs.js
music-app/src/components/dashboard/MusicPlayer.js

Co-authored-by: Jean Lafontant <jrl47@yahoo.com>

Now Like/Dislike buttons dynamically add/remove songs from playlist

---

music-app/src/actions/index.js
music-app/src/components/dashboard/MusicPlayer.js
music-app/src/views/Dashboard.js

Updated logic for creating new user in BE if non-existent
Controls when creating new playlist

Feature branch persist user update
